In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
df = pd.read_csv("../data/d10800_BS2_JoinedTrans.csv")
df.head()

,src_file,row_id,hg38_ASF1A,hg38_CCT7,hg38_EPOR,hg38_NECAP2,hg38_LRRC8A,hg38_NDUFS8,hg38_MRPL22,hg38_HIST1H2BC,...,hg38_TBC1D10C,hg38_TMEM128,hg38_ASPSCR1,hg38_CDC20,hg38_DNAJB9,hg38_OSTM1,hg38_LCNL1,hg38_PHB,hg38_LRRC29,hg38_ZFP36
0,BS2__BC__B_cells_B_V2-Brep1-BROADS2-CHECKED-VB,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,BS2__BC__B_cells_B_V2-Brep1-BROADS2-CHECKED-VB,2,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,BS2__BC__B_cells_B_V2-Brep1-BROADS2-CHECKED-VB,3,1,1,0,1,1,0,0,0,...,1,0,0,0,0,0,0,0,0,1
3,BS2__BC__B_cells_B_V2-Brep1-BROADS2-CHECKED-VB,4,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,BS2__BC__B_cells_B_V2-Brep1-BROADS2-CHECKED-VB,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2

In [3]:
X = df.drop(columns=['src_file', 'row_id'])
X.head()

,hg38_ASF1A,hg38_CCT7,hg38_EPOR,hg38_NECAP2,hg38_LRRC8A,hg38_NDUFS8,hg38_MRPL22,hg38_HIST1H2BC,hg38_LY96,hg38_UBE2E2-AS1,...,hg38_TBC1D10C,hg38_TMEM128,hg38_ASPSCR1,hg38_CDC20,hg38_DNAJB9,hg38_OSTM1,hg38_LCNL1,hg38_PHB,hg38_LRRC29,hg38_ZFP36
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2,1,1,0,1,1,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2

In [4]:
X = X.apply(pd.to_numeric, downcast='integer')

In [5]:
X.shape

(12146, 10800)

In [6]:
y = df['src_file']

In [7]:
from sklearn.feature_selection import VarianceThreshold
from scipy.sparse import csr_matrix

In [8]:
X_sparse = csr_matrix(X)
X_sparse.shape

(12146, 10800)

In [9]:
selector = VarianceThreshold(threshold=0.05)
X_selected = selector.fit_transform(X_sparse)
X_selected

<12146x5115 sparse matrix of type '<class 'numpy.int8'>'
	with 9914362 stored elements in Compressed Sparse Row format>

In [10]:
X = pd.DataFrame(X_selected.todense())
X.head()

,0,1,2,3,4,5,6,7,8,9,...,5105,5106,5107,5108,5109,5110,5111,5112,5113,5114
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
2,1,1,1,1,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,1
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,2

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [12]:
string_to_int_mapping = {string: index for index, string in enumerate(np.unique(y))}

y_mapped = np.array([string_to_int_mapping[string] for string in y])

string_to_int_mapping

{'BS2__BC__B_cells_B_V2-Brep1-BROADS2-CHECKED-VB': 0,
 'BS2__BC__B_cells_B_V2_Arep1-BROADS2-CHECKED-VB': 1,
 'BS2__BC__B_cells_B_V2_Arep2-BROADS2-CHECKED-VB': 2,
 'BS2__BC__B_cells_B_V3_Arep1-BROADS2-CHECKED-VB': 3,
 'BS2__DC__DC_cells_DC_V2_Arep1-BROADS2-CHECKED-VB': 4,
 'BS2__DC__DC_cells_DC_V2_Arep2-BROADS2-CHECKED-VB': 5,
 'BS2__DC__DC_cells_DC_V2_Brep1-BROADS2-CHECKED-VB': 6,
 'BS2__DC__DC_cells_DC_V3_Arep1-BROADS2-CHECKED-VB': 7,
 'BS2__DC__DC_cells_pDC_V2_Arep1-BROADS2-CHECKED-VB': 8,
 'BS2__DC__DC_cells_pDC_V2_Arep2-BROADS2-CHECKED-VB': 9,
 'BS2__DC__DC_cells_pDC_V2_Brep1-BROADS2-CHECKED-VB': 10,
 'BS2__MC__Monocytes_CD14+M_V2_Arep1-BROADS2-CHECKED-VB': 11,
 'BS2__MC__Monocytes_CD14+M_V2_Arep2_BROADS2_qc': 12,
 'BS2__MC__Monocytes_CD14+M_V2_Brep1-BROADS2-CHECKED-VB': 13,
 'BS2__MC__Monocytes_CD14+M_V3_Arep1-BROADS2-CHECKED-VB': 14,
 'BS2__MC__Monocytes_CD16+M_V2_Arep1-BROADS2-CHECKED-VB': 15,
 'BS2__MC__Monocytes_CD16+M_V2_Arep2-BROADS2-CHECKED-VB': 16,
 'BS2__MC__Monocytes_CD16+M_V2_Brep1-BROADS2-CHECKED-VB': 17,
 'BS2__MC__Monocytes_CD16+M_V3_Arep1-BROADS2-CHECKED-VB': 18,
 'BS2__NK__NK_cells_NK_V2_Arep1_BROADS2-CHECKED-VB': 19,
 'BS2__NK__NK_cells_NK_V2_Arep2_BROADS2-CHECKED-VB': 20,
 'BS2__NK__NK_cells_NK_V2_Brep1_BROADS2-CHECKED-VB': 21,
 'BS2__NK__NK_cells_NK_V3_Arep1_BROADS2-CHECKED-VB': 22,
 'BS2__TC__T_cells_T4_V2_Arep1_BROADS2-CHECKED-VB': 23,
 'BS2__TC__T_cells_T4_V2_Arep2_BROADS2-CHECKED-VB': 24,
 'BS2__TC__T_cells_T4_V2_Brep1_BROADS2-CHECKED-VB': 25,
 'BS2__TC__T_cells_T4_V3_Arep1_BROADS2-CHECKED-VB': 26,
 'BS2__TC__T_cells_T8_V2_Arep1-BROADS2-CHECKED-VB': 27,
 'BS2__TC__T_cells_T8_V2_Arep2-BROADS2-CHECKED-VB': 28,
 'BS2__TC__T_cells_T8_V2_Brep1-BROADS2-CHECKED-VB': 29,
 'BS2__TC__T_cells_T8_V3_Arep1-BROADS2-CHECKED-VB': 30}

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_mapped, test_size=0.3, stratify=y, random_state=0)

In [14]:
from joblib import dump
dump((X_train, X_test, y_train, y_test), 'preprocessed_data_BS2.joblib')

['preprocessed_data_BS2.joblib']

In [15]:
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

model = XGBClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.90