In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
df = pd.read_csv("../data/d10800_BS1_JoinedTrans.csv")
df.head()

,src_file,row_id,hg38_ASF1A,hg38_CCT7,hg38_EPOR,hg38_NECAP2,hg38_LRRC8A,hg38_NDUFS8,hg38_MRPL22,hg38_HIST1H2BC,...,hg38_TBC1D10C,hg38_TMEM128,hg38_ASPSCR1,hg38_CDC20,hg38_DNAJB9,hg38_OSTM1,hg38_LCNL1,hg38_PHB,hg38_LRRC29,hg38_ZFP36
0,BS1__BC__1-OK-B_cells_Bmemory-580-BOS-BROADS1-...,5,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,BS1__BC__1-OK-B_cells_Bmemory-580-BOS-BROADS1-...,13,0,0,0,3,0,3,0,0,...,0,0,0,0,0,0,0,0,0,0
2,BS1__BC__1-OK-B_cells_Bmemory-580-BOS-BROADS1-...,19,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,2,0,3
3,BS1__BC__1-OK-B_cells_Bmemory-580-BOS-BROADS1-...,21,0,0,0,0,0,3,0,0,...,0,0,0,0,3,0,0,3,0,0
4,BS1__BC__1-OK-B_cells_Bmemory-580-BOS-BROADS1-...,26,0,0,0,0,0,3,0,0,...,3,0,0,0,0,0,0,0,0,0

In [3]:
X = df.drop(columns=['src_file', 'row_id'])
X.head()

,hg38_ASF1A,hg38_CCT7,hg38_EPOR,hg38_NECAP2,hg38_LRRC8A,hg38_NDUFS8,hg38_MRPL22,hg38_HIST1H2BC,hg38_LY96,hg38_UBE2E2-AS1,...,hg38_TBC1D10C,hg38_TMEM128,hg38_ASPSCR1,hg38_CDC20,hg38_DNAJB9,hg38_OSTM1,hg38_LCNL1,hg38_PHB,hg38_LRRC29,hg38_ZFP36
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,3,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,2,0,0,2,0,3
3,0,0,0,0,0,3,0,0,0,0,...,0,0,0,0,3,0,0,3,0,0
4,0,0,0,0,0,3,0,0,0,0,...,3,0,0,0,0,0,0,0,0,0

In [4]:
X = X.apply(pd.to_numeric, downcast='integer')

In [5]:
X.shape

(13183, 10800)

In [6]:
y = df['src_file']

In [7]:
from sklearn.feature_selection import VarianceThreshold
from scipy.sparse import csr_matrix

In [8]:
X_sparse = csr_matrix(X)
X_sparse.shape

(13183, 10800)

In [9]:
selector = VarianceThreshold(threshold=0.05)
X_selected = selector.fit_transform(X_sparse)
X_selected

<13183x8123 sparse matrix of type '<class 'numpy.int8'>'
	with 11411028 stored elements in Compressed Sparse Row format>

In [10]:
X = pd.DataFrame(X_selected.todense())
X.head()

,0,1,2,3,4,5,6,7,8,9,...,8113,8114,8115,8116,8117,8118,8119,8120,8121,8122
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,3,0,3,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,2,0,0,2,3
3,0,0,0,0,0,3,0,0,0,0,...,0,0,0,0,0,3,0,0,3,0
4,0,0,0,0,0,3,0,0,0,0,...,0,0,3,0,0,0,0,0,0,0

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [12]:
string_to_int_mapping = {string: index for index, string in enumerate(np.unique(y))}

y_mapped = np.array([string_to_int_mapping[string] for string in y])

string_to_int_mapping

{'BS1__BC__1-OK-B_cells_Bmemory-580-BOS-BROADS1-CHECKED_VB': 0,
 'BS1__BC__1-OK-B_cells_Bmemory-580-NYC-BROADS1-CHECKED_VB': 1,
 'BS1__BC__1-OK-B_cells_Bmemory-860-BOS-BROADS1-CHECKED_VB': 2,
 'BS1__BC__1-OK-B_cells_Bmemory-860-NYC-BROADS1-CHECKED_VB': 3,
 'BS1__BC__1-OK-B_cells_Bnaive-580-BOS-BROADS1-CHECKED_VB': 4,
 'BS1__BC__1-OK-B_cells_Bnaive-580-NYC-BROADS1-CHECKED_VB': 5,
 'BS1__BC__1-OK-B_cells_Bnaive-860-BOS-BROADS1-CHECKED_VB': 6,
 'BS1__BC__1-OK-B_cells_Bnaive-860-NYC-BROADS1-CHECKED_VB': 7,
 'BS1__DC__1-OK-DC_cells_ALL-580-BOS-BROADS1-CHECKED_VB': 8,
 'BS1__DC__1-OK-DC_cells_ALL-580-NYC-BROADS1-CHECKED_VB': 9,
 'BS1__DC__1-OK-DC_cells_ALL-860-BOS-BROADS1-CHECKED_VB': 10,
 'BS1__DC__1-OK-DC_cells_ALL-860-NYC-BROADS1-CHECKED_VB': 11,
 'BS1__MC__1-OK-Monocytes_CD14+M-580-BOS-BROADS1-CHECKED_VB': 12,
 'BS1__MC__1-OK-Monocytes_CD14+M-580-NYC-BROADS1-CHECKED_VB': 13,
 'BS1__MC__1-OK-Monocytes_CD14+M-860-BOS-BROADS1-CHECKED_VB': 14,
 'BS1__MC__1-OK-Monocytes_CD14+M-860-NYC-BROADS1-CHECKED_VB': 15,
 'BS1__MC__1-OK-Monocytes_CD16+M-580-BOS-BROADS1-CHECKED_VB': 16,
 'BS1__MC__1-OK-Monocytes_CD16+M-580-NYC-BROADS1-CHECKED_VB': 17,
 'BS1__MC__1-OK-Monocytes_CD16+M-860-BOS-BROADS1-CHECKED_VB': 18,
 'BS1__MC__1-OK-Monocytes_CD16+M-860-NYC-BROADS1-CHECKED_VB': 19,
 'BS1__NK__1-OK-NK_cells_ALL-580-BOS-BROADS1-CHECKED_VB': 20,
 'BS1__NK__1-OK-NK_cells_ALL-580-NYC-BROADS1-CHECKED_VB': 21,
 'BS1__NK__1-OK-NK_cells_ALL-860-BOS-BROADS1-CHECKED_VB': 22,
 'BS1__NK__1-OK-NK_cells_ALL-860-NYC-BROADS1-CHECKED_VB': 23,
 'BS1__TC__1-OK-T_cells_NonClassicalT-580-BOS-BROADS1-CHECKED_VB': 24,
 'BS1__TC__1-OK-T_cells_NonClassicalT-580-NYC-BROADS1-CHECKED_VB': 25,
 'BS1__TC__1-OK-T_cells_NonClassicalT-860-BOS-BROADS1-CHECKED_VB': 26,
 'BS1__TC__1-OK-T_cells_NonClassicalT-860-NYC-BROADS1-CHECKED_VB': 27,
 'BS1__TC__1-OK-T_cells_T4eff.mem-580-BOS-BROADS1-CHECKED_VB': 28,
 'BS1__TC__1-OK-T_cells_T4eff.mem-580-NYC-BROADS1-CHECKED_VB': 29,
 'BS1__TC__1-OK-T_cells_T4eff.mem-860-BOS-BROADS1-CHECKED_VB': 30,
 'BS1__TC__1-OK-T_cells_T4eff.mem-860-NYC-BROADS1-CHECKED_VB': 31,
 'BS1__TC__1-OK-T_cells_T4naive-580-BOS-BROADS1-CHECKED_VB': 32,
 'BS1__TC__1-OK-T_cells_T4naive-580-NYC-BROADS1-CHECKED_VB': 33,
 'BS1__TC__1-OK-T_cells_T4naive-860-BOS-BROADS1-CHECKED_VB': 34,
 'BS1__TC__1-OK-T_cells_T4naive-860-NYC-BROADS1-CHECKED_VB': 35,
 'BS1__TC__1-OK-T_cells_T8eff.mem-580-BOS-BOS-BROADS1-CHECKED_VB': 36,
 'BS1__TC__1-OK-T_cells_T8eff.mem-580-NYC-BROADS1-CHECKED_VB': 37,
 'BS1__TC__1-OK-T_cells_T8eff.mem-860-BOS-BOS-BROADS1-CHECKED_VB': 38,
 'BS1__TC__1-OK-T_cells_T8eff.mem-860-NYC-BROADS1-CHECKED_VB': 39,
 'BS1__TC__1-OK-T_cells_T8naive-580-BOS-BROADS1-CHECKED_VB': 40,
 'BS1__TC__1-OK-T_cells_T8naive-580-NYC-BROADS1-CHECKED_VB': 41,
 'BS1__TC__1-OK-T_cells_T8naive-860-BROADS1-CHECKED_VB': 42,
 'BS1__TC__1-OK-T_cells_T8naive-860-NYC-BROADS1-CHECKED_VB': 43,
 'BS1__TC__1-OK-T_cells_aTreg-580-BOS-BROADS1-CHECKED_VB': 44,
 'BS1__TC__1-OK-T_cells_aTreg-580-NYC-BROADS1-CHECKED_VB': 45,
 'BS1__TC__1-OK-T_cells_aTreg-860-BOS-BROADS1-CHECKED_VB': 46,
 'BS1__TC__1-OK-T_cells_aTreg-860-NYC-BROADS1-CHECKED_VB': 47,
 'BS1__TC__1-OK-T_cells_nonT-580-BOS-BROADS1-CHECKED_VB': 48,
 'BS1__TC__1-OK-T_cells_nonT-580-NYC-BROADS1-CHECKED_VB': 49,
 'BS1__TC__1-OK-T_cells_nonT-860-BOS-BROADS1-CHECKED_VB': 50,
 'BS1__TC__1-OK-T_cells_nonT-860-NYC-BROADS1-CHECKED_VB': 51,
 'BS1__TC__1-OK-T_cells_rTreg-580-BOS-BROADS1-CHECKED_VB': 52,
 'BS1__TC__1-OK-T_cells_rTreg-580-NYC-BROADS1-CHECKED_VB': 53,
 'BS1__TC__1-OK-T_cells_rTreg-860-BOS-BROADS1-CHECKED_VB': 54,
 'BS1__TC__1-OK-T_cells_rTreg-860-NYC-BROADS1-CHECKED_VB': 55}

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y_mapped, test_size=0.3, stratify=y, random_state=0)

In [14]:
from joblib import dump
dump((X_train, X_test, y_train, y_test), 'preprocessed_data_BS1.joblib')

['preprocessed_data_BS1.joblib']

In [15]:
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier

model = XGBClassifier()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

Accuracy: 0.61